#!/usr/bin/env bash
#
# Generates a coturn configuration for relaying Vector call media, with a fresh
# random credential, and prints the client build flags that go with it.
#
# TURN is off by default in the client on purpose (SECURITY.md). Running this
# accepts that the relay learns who called whom, for how long, and from where.
# It cannot listen to the call: media stays DTLS-SRTP encrypted end to end.
#
# Usage:
#   ./make-turn-config.sh <realm-hostname> [public-ip]
#
# Example:
#   ./make-turn-config.sh c2.84ace.com
#
# The public IP is detected if not supplied. On a dynamic address behind DDNS,
# pass it explicitly or re-run this after it changes — coturn reads the config
# once at startup and advertises that address in every candidate it hands out.
#
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: $0 <realm-hostname> [public-ip]" >&2
  exit 64
fi

REALM="$1"
PUBLIC_IP="${2:-}"
OUT_DIR="${OUT_DIR:-./certs}"
TURN_USER="${TURN_USER:-vector}"

# Where certbot keeps its state. Not always /etc/letsencrypt: a deployment that
# runs certbot in a container — which is how the c2.84ace.com certificate is
# issued, see DEPLOYMENT.md — has it wherever that container's volume is mounted.
LE_DIR="${LE_DIR:-/etc/letsencrypt}"

# nobody:nogroup inside coturn/coturn:*-alpine. See the chown below for why this
# matters more than it looks.
COTURN_UID="${COTURN_UID:-65534}"
COTURN_GID="${COTURN_GID:-65533}"

# Relay port range. Each concurrent call takes one port per participant; 40 is
# ample for a squad and keeps the firewall rule small.
MIN_PORT="${MIN_PORT:-49160}"
MAX_PORT="${MAX_PORT:-49200}"

if [[ -z "$PUBLIC_IP" ]]; then
  echo "Detecting public address..." >&2
  PUBLIC_IP="$(curl -fsS --max-time 10 https://api.ipify.org || true)"
  if [[ -z "$PUBLIC_IP" ]]; then
    echo "error: could not detect the public IP. Pass it as the second argument." >&2
    exit 1
  fi
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "error: openssl is required to generate a credential" >&2
  exit 1
fi

# 128 bits, base64url. This is a long-term credential that ends up inside the
# app binary, so it has to be unguessable — see the warning printed at the end
# for what that does and does not protect.
TURN_SECRET="$(openssl rand -base64 24 | tr '+/' '-_' | tr -d '=\n')"

mkdir -p "$OUT_DIR"
CONF="$OUT_DIR/turnserver.conf"

cat > "$CONF" <<EOF
# Generated by scripts/make-turn-config.sh for $REALM
#
# Do not commit this file: it carries the TURN credential.

listening-port=3478
tls-listening-port=5349

# The address coturn advertises in the candidates it hands out. Behind NAT this
# has to be the public address, or peers are told to send media to a private
# address they cannot reach.
external-ip=$PUBLIC_IP

realm=$REALM
fingerprint
lt-cred-mech
user=$TURN_USER:$TURN_SECRET

# TURN over TLS uses the same certificate the relay is already fronted with.
cert=/certs/fullchain.pem
pkey=/certs/privkey.pem

# Relay ports handed out per session. Must be open in the firewall as UDP.
min-port=$MIN_PORT
max-port=$MAX_PORT

# --- Abuse containment -------------------------------------------------------
#
# A TURN server forwards UDP to wherever a client asks. Left open, that makes it
# a proxy into whatever network it sits on: anyone holding the credential could
# ask it to relay to 192.168.x.x and reach services on the LAN that were never
# meant to face the internet. The credential lives inside a distributed app
# binary and must be assumed extractable, so these denials are load-bearing
# rather than defence in depth.
no-multicast-peers

denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.0.0.0-192.0.0.255
denied-peer-ip=192.0.2.0-192.0.2.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=198.18.0.0-198.19.255.255
denied-peer-ip=198.51.100.0-198.51.100.255
denied-peer-ip=203.0.113.0-203.0.113.255
denied-peer-ip=240.0.0.0-255.255.255.255

denied-peer-ip=::1
denied-peer-ip=64:ff9b::-64:ff9b::ffff:ffff
denied-peer-ip=::ffff:0.0.0.0-::ffff:255.255.255.255
denied-peer-ip=fc00::-fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
denied-peer-ip=fe80::-febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff

# Caps, so a leaked credential cannot turn this into someone else's bandwidth.
user-quota=12
total-quota=60

# No admin interface: it is another listener to secure for no benefit here.
no-cli
no-tlsv1
no-tlsv1_1

# Sessions are logged, but the log is the metadata this server was warned about.
# Rotate or discard it deliberately rather than letting it accumulate forever.
log-file=stdout
simple-log
EOF

chmod 400 "$CONF"

# The coturn image runs as nobody:nogroup, and a bind mount carries host UIDs
# straight through — so a config owned by the invoking user is unreadable inside
# the container no matter what the mount says. coturn reports that as "Cannot
# find config file" and then silently starts with *defaults*: no realm, no
# credentials, and none of the denied-peer-ip rules below. A TURN server with
# its access controls quietly switched off is worse than one that fails to
# start, so hand ownership to the container's user rather than widening the mode.
if chown "$COTURN_UID:$COTURN_GID" "$CONF" 2>/dev/null; then
  :
elif sudo -n chown "$COTURN_UID:$COTURN_GID" "$CONF" 2>/dev/null; then
  :
else
  echo
  echo "WARNING: could not chown $CONF to $COTURN_UID:$COTURN_GID."
  echo "         coturn runs as that uid and will not be able to read it — it will"
  echo "         start with defaults and NO access controls. Fix with:"
  echo "           sudo chown $COTURN_UID:$COTURN_GID $CONF"
  echo
fi

cat <<EOF

Wrote $CONF

--- Certificate ------------------------------------------------------------

coturn needs the certificate for $REALM at $OUT_DIR/turn/:

  mkdir -p $OUT_DIR/turn
  sudo cp -L $LE_DIR/live/$REALM/fullchain.pem $OUT_DIR/turn/
  sudo cp -L $LE_DIR/live/$REALM/privkey.pem   $OUT_DIR/turn/
  sudo chown $COTURN_UID:$COTURN_GID $OUT_DIR/turn/fullchain.pem $OUT_DIR/turn/privkey.pem
  sudo chmod 444 $OUT_DIR/turn/fullchain.pem
  sudo chmod 400 $OUT_DIR/turn/privkey.pem

privkey.pem under live/ is normally root-only, hence sudo. The chown is for the
same reason as the config above: coturn runs as $COTURN_UID and cannot read a
file owned by you, and it treats an unreadable certificate as an absent one —
falling back to no TLS listener at all with only a warning.

Those paths come from LE_DIR, currently "$LE_DIR". If certbot runs in a container
its state is wherever that volume is mounted, not /etc/letsencrypt — re-run with
LE_DIR=... set, or copy the two files by hand.

cp is deliberate rather than a symlink: the files under live/ are themselves
symlinks into archive/, and the container would have to be able to follow them
out of the mount to resolve one.

Renewal has to restart coturn: like the relay, it reads the certificate once at
startup and does not watch the file.

--- Firewall ---------------------------------------------------------------

Forward these to this host, or TURN cannot do its job:

  3478/udp, 3478/tcp    STUN/TURN
  5349/tcp              TURN over TLS
  $MIN_PORT-$MAX_PORT/udp    relay ports

--- Start it ---------------------------------------------------------------

  docker compose -f docker-compose.yml -f docker-compose.turn.yml up -d

--- Build the client -------------------------------------------------------

  cd ../client && flutter build apk --release \\
    --dart-define=CLOUD_MESH_NODE_URL=https://$REALM \\
    --dart-define=TRANSPORT_POLICY=tls-only \\
    --dart-define=TURN_URLS=turns:$REALM:5349 \\
    --dart-define=TURN_USERNAME=$TURN_USER \\
    --dart-define=TURN_CREDENTIAL=$TURN_SECRET

--- Understand what you just accepted --------------------------------------

This credential is compiled into the app and must be assumed recoverable by
anyone holding a build. That is why the denied-peer-ip block above exists: it
stops a recovered credential being used to reach your LAN. Rotate it by
re-running this script and rebuilding the clients.

The app writes an advisory into the operator's event log naming this relay
whenever TURN is configured, because a TURN server sees both endpoints'
addresses and the full media stream. It cannot decrypt the call.

EOF
